[tool.poetry]
name = "poetry-flask-demo"
version = "0.1.0"
description = "Learning Python with Flask!"
authors = ["Fergus Thufuss <fthufuss@tk3c.net>"]

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.0.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
